# server配置
server:
  port: 8080
  servlet:
    context-path: /

# 连接池配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql:///dp_management
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
  data: # redis配置
    redis:
      host: 127.0.0.1
      port: 6380
      password: 123456

# mybatis-plus的配置
mybatis-plus:
  type-aliases-package: website.hehe.pojo
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
  global-config:
    db-config:
      logic-delete-field: isDeleted  #全局逻辑删除

# jwt配置
jwt:
  token:
    tokenExpiration: 120 #有效时间,单位分钟 (7days)

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: metrics, health, info
  info:
    env:
      enabled: true
info:
  project:
    name: "Student DP Management System"
    url: https://github.com/Ijusthahaha/dp_backend